#!/bin/python3

import os

# Complete the equal function below.
def equal(arr):
    m=min(arr)
    t=[0]*4
    for i in arr:
        for j in range(4):
            x=i-(m-j)
            x=(x//5)+((x%5)//2)+((x%5)%2)
            t[j] +=x

    return min(t)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        arr = list(map(int, input().rstrip().split()))

        result = equal(arr)

        fptr.write(str(result) + '\n')

    fptr.close()
